### ISSUE TITLE
Mailer delivery DSL

### ISSUE THREAD

**Issue by jodosha** [lotus/mailer#3]
When a Ruby object includes `Lotus::Mailer`, a developer can customize delivery details.

## From

This is the field that will determine the sender of the email.

```ruby
class InvoiceMailer
  include Lotus::Mailer

  from "noreply@example.com"
  # or
  from -> { customized_sender }

  def customized_sender
    "user-#{ user.id }@example.com"
  end
end
```

It can accept a string or a Proc, to determine the value.

In case of a Proc, it MUST be used when the mailer is initialized and the block evaluated in the context of that instance. Ruby's `instance_eval` is your friend ;)

## To

This represent one or more email addresses that will be the recipients of the mail.
The DSL is similar to `from`, and we want to be able to accept both String and Proc.

## Subject

This is the subject of the message.
The DSL is similar to `from`, and we want to be able to accept both String and Proc.

**Comment by cweyer** [comment]
I think for To: we should also accept Array
