### ISSUE TITLE
prepare block in the lib/ configuration doesn't work due to load order

### ISSUE THREAD

**Issue by louisgillies** [lotus/mailer#40]
given a new app created using 
`lotus new demo`

and a new mailer created using 
`lotus generate mailer Welcome`

and a shared module to set the `from` in all mailers following the guide here http://lotusrb.org/guides/mailers/share-code/

then the configuration block in the generated 'lib/demo.rb' file as follows:

```ruby
require 'lotus/model'
require 'lotus/mailer'
Dir["#{ __dir__ }/demo/**/*.rb"].each { |file| require_relative file }

Lotus::Model.configure do
  ##
  # Database adapter
  #
  # Available options:
  #
  #  * Memory adapter
  #    adapter type: :memory, uri: 'memory://localhost/demo_development'
  #
  #  * SQL adapter
  #    adapter type: :sql, uri: 'sqlite://db/demo_development.sqlite3'
  #    adapter type: :sql, uri: 'postgres://localhost/demo_development'
  #    adapter type: :sql, uri: 'mysql://localhost/demo_development'
  #
  adapter type: :file_system, uri: ENV['DEMO_DATABASE_URL']

  ##
  # Database mapping
  #
  # Intended for specifying application wide mappings.
  #
  # You can specify mapping file to load with:
  #
  # mapping "#{__dir__}/config/mapping"
  #
  # Alternatively, you can use a block syntax like the following:
  #
  mapping do
    # collection :users do
    #   entity     User
    #   repository UserRepository
    #
    #   attribute :id,   Integer
    #   attribute :name, String
    # end
  end
end.load!

Lotus::Mailer.configure do
  root "#{ __dir__ }/demo/mailers"

  # See http://lotusrb.org/guides/mailers/delivery
  delivery do
    development :test
    test        :test
    # production :stmp, address: ENV['SMTP_PORT'], port: 1025
  end

  prepare do
    include Mailers::DefaultSender
  end
end.load!

```

This doesn't work as the included hook of the `lib/demo/mailers/welcome.rb` class when including `Lotus::Mailers` gets called before the configuration for the shared code is defined as one of the *globbed* require_relatives in `Dir["#{ __dir__ }/demo/**/*.rb"].each { |file| require_relative file }` and the underlying `.copy!` method is called before there is anything configured https://github.com/lotus/mailer/blob/master/lib/lotus/mailer.rb#L89

Perhaps this isn't a bug and I'm just placing configuration in the wrong place? If it is I'm happy to help out in any way I can.

Thanks

Louis

**Comment by joneslee85** [comment]
@louisgillies thanks for the bug report and sorry for late reply. When you are online, please ping me on chat room, I just want to ask few questions

**Comment by jodosha** [comment]
@louisgillies We had an internal discussion on how to solve this problem and other small discrepancies in the design. Unfortunately there isn't a design solution that works for all these issues. For each potential way, there is a pitfall.

We want to wait until we find something that is solid enough to be included in the framework as the way to go.

As a workaround in your code you can break the eager loading strategy:

```ruby
require 'lotus/model'
require 'lotus/mailer'
require_relative './demo/mailers/default_sender'
Dir["#{ __dir__ }/demo/{entities,repositories}/*.rb"].each { |file| require_relative file }

Lotus::Model.configure do
  # ...
end.load!

Lotus::Mailer.configure do
  # ...

  prepare do
    include Mailers::DefaultSender
  end
end.load!

Dir["#{ __dir__ }/demo/mailers/*.rb"].each { |file| require_relative file }
```
