### ISSUE TITLE
Rendering Context

### ISSUE THREAD

**Issue by jodosha** [lotus/mailer#5]
When a mailer renders a template (#4 ), we want to be able to interpolate parts of it, with values coming from the mailer itself.

For instance, if we have the following template:

```erb
Hello <%= user.name %>,
```

We want to be able to replace `<%= user.name %>` with the actual name of the current user.

We MUST have two sources for these values (simplified version of Lotus::View).

## Concrete Methods

If a mailer defines a concrete method, it must be available as rendering context for the template.

```ruby
class WelcomeMailer
  include Lotus::Mailer

  def greeting
    "Ahoy"
  end
end
```

```erb
<%= greeting %>!
```

## Locals

The other source is named _locals_. It's a set of objects passed to the constructor.

```ruby
class InvitationMailer
  include Lotus::Mailer
end

luca = User.new(first_name: 'Luca', username: 'jodosha')
mailer = InvoiceMailer.new(user: luca)
```

Then we MUST be able to use `user` from the template.

**Please note that the name of the key (`:user`) is important in this process.**
If we change it with `:person`, then we must reference that object as `person` in the template.

**Comment by inescoelho** [comment]
In "Locals", mailers is supposed to initialize an InvoiceMailer object or an InvitationMailer object?

**Comment by joneslee85** [comment]
@inescoelho I think it is typo, it should be `InvitationMailer`
