### ISSUE TITLE
Delivery Method

### ISSUE THREAD

**Issue by jodosha** [lotus/mailer#6]
Let developers to specify a global delivery method.
This is done via the framework configuration (#1 ).

```ruby
Lotus::Mailer.configure do
  # ...
  delivery_method :sendmail

  # or
  delivery_method :smtp, address: "localhost", port: 1025

  # or
  delivery :test

  # or
  delivery_method MyCustomDeliveryMethod, foo: 'bar'
end
```

Lotus::Mailer will depend on `mail` gem. This library already supports this scenario.
Our goal is to store that settings and to pass them at the **single mail instance**, that we're gonna to deliver.

In other words, we MUST avoid this:

```ruby
Mail.defaults do
  delivery_method :smtp, address: "localhost", port: 1025
end
```

In favor of this:

```ruby
mail = Mail.new
mail.delivery_method Lotus::Mailer.configuration.delivery_method
```

**Comment by rosafaria** [comment]
Should the delivery method be the same for all mailers?
