### ISSUE TITLE
Multipart delivery

### ISSUE THREAD

**Issue by jodosha** [lotus/mailer#7]
When a class includes `Lotus::Mailer`, then it will expose `.render`.
It delivers a multipart email, by looking at all the associated templates (#2) and render them ( #4 ).
It accepts a set of locals (#5 ), instantiate a mailer and deliver the email.

```ruby
InvoiceMailer.deliver(user: user, invoice: invoice)
```

Under the hood it will look like this:

```ruby
def self.deliver(locals)
  new(locals).deliver
end
```

Please note that once a mailer is instantiate, it MUST be immutable.

**Comment by inescoelho** [comment]
@joneslee85 Is the exposed method `.render` or `.deliver`?

**Comment by joneslee85** [comment]
@inescoelho should be `deliver`
